#pragma once
inline constexpr unsigned short int KEY_SPACE = 32;
inline constexpr unsigned short int KEY_APOSTROPHE = 39; /* ' */
inline constexpr unsigned short int KEY_COMMA = 44;      /* , */
inline constexpr unsigned short int KEY_MINUS = 45;      /* - */
inline constexpr unsigned short int KEY_PERIOD = 46;     /* . */
inline constexpr unsigned short int KEY_SLASH = 47;      /* / */
inline constexpr unsigned short int KEY_0 = 48;
inline constexpr unsigned short int KEY_1 = 49;
inline constexpr unsigned short int KEY_2 = 50;
inline constexpr unsigned short int KEY_3 = 51;
inline constexpr unsigned short int KEY_4 = 52;
inline constexpr unsigned short int KEY_5 = 53;
inline constexpr unsigned short int KEY_6 = 54;
inline constexpr unsigned short int KEY_7 = 55;
inline constexpr unsigned short int KEY_8 = 56;
inline constexpr unsigned short int KEY_9 = 57;
inline constexpr unsigned short int KEY_SEMICOLON = 59; /* ; */
inline constexpr unsigned short int KEY_EQUAL = 61;     /* = */
inline constexpr unsigned short int KEY_A = 65;
inline constexpr unsigned short int KEY_B = 66;
inline constexpr unsigned short int KEY_C = 67;
inline constexpr unsigned short int KEY_D = 68;
inline constexpr unsigned short int KEY_E = 69;
inline constexpr unsigned short int KEY_F = 70;
inline constexpr unsigned short int KEY_G = 71;
inline constexpr unsigned short int KEY_H = 72;
inline constexpr unsigned short int KEY_I = 73;
inline constexpr unsigned short int KEY_J = 74;
inline constexpr unsigned short int KEY_K = 75;
inline constexpr unsigned short int KEY_L = 76;
inline constexpr unsigned short int KEY_M = 77;
inline constexpr unsigned short int KEY_N = 78;
inline constexpr unsigned short int KEY_O = 79;
inline constexpr unsigned short int KEY_P = 80;
inline constexpr unsigned short int KEY_Q = 81;
inline constexpr unsigned short int KEY_R = 82;
inline constexpr unsigned short int KEY_S = 83;
inline constexpr unsigned short int KEY_T = 84;
inline constexpr unsigned short int KEY_U = 85;
inline constexpr unsigned short int KEY_V = 86;
inline constexpr unsigned short int KEY_W = 87;
inline constexpr unsigned short int KEY_X = 88;
inline constexpr unsigned short int KEY_Y = 89;
inline constexpr unsigned short int KEY_Z = 90;
inline constexpr unsigned short int KEY_LEFT_BRACKET = 91;  /* [ */
inline constexpr unsigned short int KEY_BACKSLASH = 92;     /* \ */
inline constexpr unsigned short int KEY_RIGHT_BRACKET = 93; /* ] */
inline constexpr unsigned short int KEY_GRAVE_ACCENT = 96;  /* ` */
inline constexpr unsigned short int KEY_WORLD_1 = 161;      /* non-US #1 */
inline constexpr unsigned short int KEY_WORLD_2 = 162;      /* non-US #2 */
inline constexpr unsigned short int KEY_ESCAPE = 256;
inline constexpr unsigned short int KEY_ENTER = 257;
inline constexpr unsigned short int KEY_TAB = 258;
inline constexpr unsigned short int KEY_BACKSPACE = 259;
inline constexpr unsigned short int KEY_INSERT = 260;
inline constexpr unsigned short int KEY_DELETE = 261;
inline constexpr unsigned short int KEY_RIGHT = 262;
inline constexpr unsigned short int KEY_LEFT = 263;
inline constexpr unsigned short int KEY_DOWN = 264;
inline constexpr unsigned short int KEY_UP = 265;
inline constexpr unsigned short int KEY_PAGE_UP = 266;
inline constexpr unsigned short int KEY_PAGE_DOWN = 267;
inline constexpr unsigned short int KEY_HOME = 268;
inline constexpr unsigned short int KEY_END = 269;
inline constexpr unsigned short int KEY_CAPS_LOCK = 280;
inline constexpr unsigned short int KEY_SCROLL_LOCK = 281;
inline constexpr unsigned short int KEY_NUM_LOCK = 282;
inline constexpr unsigned short int KEY_PRINT_SCREEN = 283;
inline constexpr unsigned short int KEY_PAUSE = 284;
inline constexpr unsigned short int KEY_F1 = 290;
inline constexpr unsigned short int KEY_F2 = 291;
inline constexpr unsigned short int KEY_F3 = 292;
inline constexpr unsigned short int KEY_F4 = 293;
inline constexpr unsigned short int KEY_F5 = 294;
inline constexpr unsigned short int KEY_F6 = 295;
inline constexpr unsigned short int KEY_F7 = 296;
inline constexpr unsigned short int KEY_F8 = 297;
inline constexpr unsigned short int KEY_F9 = 298;
inline constexpr unsigned short int KEY_F10 = 299;
inline constexpr unsigned short int KEY_F11 = 300;
inline constexpr unsigned short int KEY_F12 = 301;
inline constexpr unsigned short int KEY_F13 = 302;
inline constexpr unsigned short int KEY_F14 = 303;
inline constexpr unsigned short int KEY_F15 = 304;
inline constexpr unsigned short int KEY_F16 = 305;
inline constexpr unsigned short int KEY_F17 = 306;
inline constexpr unsigned short int KEY_F18 = 307;
inline constexpr unsigned short int KEY_F19 = 308;
inline constexpr unsigned short int KEY_F20 = 309;
inline constexpr unsigned short int KEY_F21 = 310;
inline constexpr unsigned short int KEY_F22 = 311;
inline constexpr unsigned short int KEY_F23 = 312;
inline constexpr unsigned short int KEY_F24 = 313;
inline constexpr unsigned short int KEY_F25 = 314;
inline constexpr unsigned short int KEY_KP_0 = 320;
inline constexpr unsigned short int KEY_KP_1 = 321;
inline constexpr unsigned short int KEY_KP_2 = 322;
inline constexpr unsigned short int KEY_KP_3 = 323;
inline constexpr unsigned short int KEY_KP_4 = 324;
inline constexpr unsigned short int KEY_KP_5 = 325;
inline constexpr unsigned short int KEY_KP_6 = 326;
inline constexpr unsigned short int KEY_KP_7 = 327;
inline constexpr unsigned short int KEY_KP_8 = 328;
inline constexpr unsigned short int KEY_KP_9 = 329;
inline constexpr unsigned short int KEY_KP_DECIMAL = 330;
inline constexpr unsigned short int KEY_KP_DIVIDE = 331;
inline constexpr unsigned short int KEY_KP_MULTIPLY = 332;
inline constexpr unsigned short int KEY_KP_SUBTRACT = 333;
inline constexpr unsigned short int KEY_KP_ADD = 334;
inline constexpr unsigned short int KEY_KP_ENTER = 335;
inline constexpr unsigned short int KEY_KP_EQUAL = 336;
inline constexpr unsigned short int KEY_LEFT_SHIFT = 340;
inline constexpr unsigned short int KEY_LEFT_CONTROL = 341;
inline constexpr unsigned short int KEY_LEFT_ALT = 342;
inline constexpr unsigned short int KEY_LEFT_SUPER = 343;
inline constexpr unsigned short int KEY_RIGHT_SHIFT = 344;
inline constexpr unsigned short int KEY_RIGHT_CONTROL = 345;
inline constexpr unsigned short int KEY_RIGHT_ALT = 346;
inline constexpr unsigned short int KEY_RIGHT_SUPER = 347;
inline constexpr unsigned short int KEY_MENU = 348;