#pragma once
constexpr unsigned short int KEY_SPACE = 32;
constexpr unsigned short int KEY_APOSTROPHE = 39; /* ' */
constexpr unsigned short int KEY_COMMA = 44; /* , */
constexpr unsigned short int KEY_MINUS = 45; /* - */
constexpr unsigned short int KEY_PERIOD = 46; /* . */
constexpr unsigned short int KEY_SLASH = 47; /* / */
constexpr unsigned short int KEY_0 = 48;
constexpr unsigned short int KEY_1 = 49;
constexpr unsigned short int KEY_2 = 50;
constexpr unsigned short int KEY_3 = 51;
constexpr unsigned short int KEY_4 = 52;
constexpr unsigned short int KEY_5 = 53;
constexpr unsigned short int KEY_6 = 54;
constexpr unsigned short int KEY_7 = 55;
constexpr unsigned short int KEY_8 = 56;
constexpr unsigned short int KEY_9 = 57;
constexpr unsigned short int KEY_SEMICOLON = 59; /* ; */
constexpr unsigned short int KEY_EQUAL = 61; /* = */
constexpr unsigned short int KEY_A = 65;
constexpr unsigned short int KEY_B = 66;
constexpr unsigned short int KEY_C = 67;
constexpr unsigned short int KEY_D = 68;
constexpr unsigned short int KEY_E = 69;
constexpr unsigned short int KEY_F = 70;
constexpr unsigned short int KEY_G = 71;
constexpr unsigned short int KEY_H = 72;
constexpr unsigned short int KEY_I = 73;
constexpr unsigned short int KEY_J = 74;
constexpr unsigned short int KEY_K = 75;
constexpr unsigned short int KEY_L = 76;
constexpr unsigned short int KEY_M = 77;
constexpr unsigned short int KEY_N = 78;
constexpr unsigned short int KEY_O = 79;
constexpr unsigned short int KEY_P = 80;
constexpr unsigned short int KEY_Q = 81;
constexpr unsigned short int KEY_R = 82;
constexpr unsigned short int KEY_S = 83;
constexpr unsigned short int KEY_T = 84;
constexpr unsigned short int KEY_U = 85;
constexpr unsigned short int KEY_V = 86;
constexpr unsigned short int KEY_W = 87;
constexpr unsigned short int KEY_X = 88;
constexpr unsigned short int KEY_Y = 89;
constexpr unsigned short int KEY_Z = 90;
constexpr unsigned short int KEY_LEFT_BRACKET = 91; /* [ */
constexpr unsigned short int KEY_BACKSLASH = 92; /* \ */
constexpr unsigned short int KEY_RIGHT_BRACKET = 93; /* ] */
constexpr unsigned short int KEY_GRAVE_ACCENT = 96; /* ` */
constexpr unsigned short int KEY_WORLD_1 = 161; /* non-US #1 */
constexpr unsigned short int KEY_WORLD_2 = 162; /* non-US #2 */
constexpr unsigned short int KEY_ESCAPE = 256;
constexpr unsigned short int KEY_ENTER = 257;
constexpr unsigned short int KEY_TAB = 258;
constexpr unsigned short int KEY_BACKSPACE = 259;
constexpr unsigned short int KEY_INSERT = 260;
constexpr unsigned short int KEY_DELETE = 261;
constexpr unsigned short int KEY_RIGHT = 262;
constexpr unsigned short int KEY_LEFT = 263;
constexpr unsigned short int KEY_DOWN = 264;
constexpr unsigned short int KEY_UP = 265;
constexpr unsigned short int KEY_PAGE_UP = 266;
constexpr unsigned short int KEY_PAGE_DOWN = 267;
constexpr unsigned short int KEY_HOME = 268;
constexpr unsigned short int KEY_END = 269;
constexpr unsigned short int KEY_CAPS_LOCK = 280;
constexpr unsigned short int KEY_SCROLL_LOCK = 281;
constexpr unsigned short int KEY_NUM_LOCK = 282;
constexpr unsigned short int KEY_PRINT_SCREEN = 283;
constexpr unsigned short int KEY_PAUSE = 284;
constexpr unsigned short int KEY_F1 = 290;
constexpr unsigned short int KEY_F2 = 291;
constexpr unsigned short int KEY_F3 = 292;
constexpr unsigned short int KEY_F4 = 293;
constexpr unsigned short int KEY_F5 = 294;
constexpr unsigned short int KEY_F6 = 295;
constexpr unsigned short int KEY_F7 = 296;
constexpr unsigned short int KEY_F8 = 297;
constexpr unsigned short int KEY_F9 = 298;
constexpr unsigned short int KEY_F10 = 299;
constexpr unsigned short int KEY_F11 = 300;
constexpr unsigned short int KEY_F12 = 301;
constexpr unsigned short int KEY_F13 = 302;
constexpr unsigned short int KEY_F14 = 303;
constexpr unsigned short int KEY_F15 = 304;
constexpr unsigned short int KEY_F16 = 305;
constexpr unsigned short int KEY_F17 = 306;
constexpr unsigned short int KEY_F18 = 307;
constexpr unsigned short int KEY_F19 = 308;
constexpr unsigned short int KEY_F20 = 309;
constexpr unsigned short int KEY_F21 = 310;
constexpr unsigned short int KEY_F22 = 311;
constexpr unsigned short int KEY_F23 = 312;
constexpr unsigned short int KEY_F24 = 313;
constexpr unsigned short int KEY_F25 = 314;
constexpr unsigned short int KEY_KP_0 = 320;
constexpr unsigned short int KEY_KP_1 = 321;
constexpr unsigned short int KEY_KP_2 = 322;
constexpr unsigned short int KEY_KP_3 = 323;
constexpr unsigned short int KEY_KP_4 = 324;
constexpr unsigned short int KEY_KP_5 = 325;
constexpr unsigned short int KEY_KP_6 = 326;
constexpr unsigned short int KEY_KP_7 = 327;
constexpr unsigned short int KEY_KP_8 = 328;
constexpr unsigned short int KEY_KP_9 = 329;
constexpr unsigned short int KEY_KP_DECIMAL = 330;
constexpr unsigned short int KEY_KP_DIVIDE = 331;
constexpr unsigned short int KEY_KP_MULTIPLY = 332;
constexpr unsigned short int KEY_KP_SUBTRACT = 333;
constexpr unsigned short int KEY_KP_ADD = 334;
constexpr unsigned short int KEY_KP_ENTER = 335;
constexpr unsigned short int KEY_KP_EQUAL = 336;
constexpr unsigned short int KEY_LEFT_SHIFT = 340;
constexpr unsigned short int KEY_LEFT_CONTROL = 341;
constexpr unsigned short int KEY_LEFT_ALT = 342;
constexpr unsigned short int KEY_LEFT_SUPER = 343;
constexpr unsigned short int KEY_RIGHT_SHIFT = 344;
constexpr unsigned short int KEY_RIGHT_CONTROL = 345;
constexpr unsigned short int KEY_RIGHT_ALT = 346;
constexpr unsigned short int KEY_RIGHT_SUPER = 347;
constexpr unsigned short int KEY_MENU = 348;