#pragma once
#include <memory>
#include <vector>

#include "Core/Typenames.h"
#include "Level/Chunk/Block/Material/BlockMaterial.h"

class TextureAtlas;

namespace Model {
    struct BlockModel;
}

class BlockList{
public:
    FastHashMap<std::string, BlockID> block_id_name_data_;

    std::vector<Block*> block_type_data_;
    std::vector<Model::BlockModel> block_model_data_;

    std::unique_ptr<TextureAtlas> block_texture_atlas_;

    BlockID AIR = RegisterBlock("minecraft:air", new MaterialNone(), true, false, false);
    BlockID NULL_BLOCK = RegisterBlock("minecraft:null", new MaterialNone(), false, false, false);
    BlockID STONE = RegisterBlock("minecraft:stone", new MaterialNone(), false, true, false);
    BlockID DIRT = RegisterBlock("minecraft:dirt", new MaterialDirt(), false, true, false);
    BlockID WATER = RegisterBlock("minecraft:water", new MaterialFluid(5), true, false, true);
    BlockID LAVA = RegisterBlock("minecraft:lava", new MaterialFluid(5), true, false, true);
    BlockID GRASS = RegisterBlock("minecraft:grass_block", new MaterialGrass(0.1, 0.1), false, true, false);
    BlockID SAND = RegisterBlock("minecraft:sand", new MaterialGravity(), false, true, false);
    BlockID OAK_LOG = RegisterBlock("minecraft:oak_log", new MaterialNone(), false, true, false);
    BlockID STRIPPED_OAK_LOG = RegisterBlock("minecraft:stripped_oak_log", new MaterialNone(), false, true, false);
    BlockID OAK_PLANKS = RegisterBlock("minecraft:oak_planks", new MaterialNone(), false, true, false);
    BlockID ACACIA_PLANKS = RegisterBlock("minecraft:acacia_planks", new MaterialNone(), false, true, false);
    BlockID BAMBOO_PLANKS = RegisterBlock("minecraft:bamboo_planks", new MaterialNone(), false, true, false);
    BlockID BIRCH_PLANKS = RegisterBlock("minecraft:birch_planks", new MaterialNone(), false, true, false);
    BlockID CHERRY_PLANKS = RegisterBlock("minecraft:cherry_planks", new MaterialNone(), false, true, false);
    BlockID CRIMSON_PLANKS = RegisterBlock("minecraft:crimson_planks", new MaterialNone(), false, true, false);
    BlockID DARK_OAK_PLANKS = RegisterBlock("minecraft:dark_oak_planks", new MaterialNone(), false, true, false);
    BlockID JUNGLE_PLANKS = RegisterBlock("minecraft:jungle_planks", new MaterialNone(), false, true, false);
    BlockID MANGROVE_PLANKS = RegisterBlock("minecraft:mangrove_planks", new MaterialNone(), false, true, false);
    BlockID SPRUCE_PLANKS = RegisterBlock("minecraft:spruce_planks", new MaterialNone(), false, true, false);
    BlockID WARPED_PLANKS = RegisterBlock("minecraft:warped_planks", new MaterialNone(), false, true, false);
    BlockID OAK_WOOD = RegisterBlock("minecraft:oak_wood", new MaterialNone(), false, true, false);
    BlockID ACACIA_WOOD = RegisterBlock("minecraft:acacia_wood", new MaterialNone(), false, true, false);
    BlockID BIRCH_WOOD = RegisterBlock("minecraft:birch_wood", new MaterialNone(), false, true, false);
    BlockID CHERRY_WOOD = RegisterBlock("minecraft:cherry_wood", new MaterialNone(), false, true, false);
    BlockID DARK_OAK_WOOD = RegisterBlock("minecraft:dark_oak_wood", new MaterialNone(), false, true, false);
    BlockID JUNGLE_WOOD = RegisterBlock("minecraft:jungle_wood", new MaterialNone(), false, true, false);
    BlockID MANGROVE_WOOD = RegisterBlock("minecraft:mangrove_wood", new MaterialNone(), false, true, false);
    BlockID SPRUCE_WOOD = RegisterBlock("minecraft:spruce_wood", new MaterialNone(), false, true, false);
    BlockID STRIPPED_OAK_WOOD = RegisterBlock("minecraft:stripped_oak_wood", new MaterialNone(), false, true, false);
    BlockID STRIPPED_ACACIA_WOOD = RegisterBlock("minecraft:stripped_acacia_wood", new MaterialNone(), false, true, false);
    BlockID STRIPPED_BIRCH_WOOD = RegisterBlock("minecraft:stripped_birch_wood", new MaterialNone(), false, true, false);
    BlockID STRIPPED_CHERRY_WOOD = RegisterBlock("minecraft:stripped_cherry_wood", new MaterialNone(), false, true, false);
    BlockID STRIPPED_DARK_OAK_WOOD = RegisterBlock("minecraft:stripped_dark_oak_wood", new MaterialNone(), false, true, false);
    BlockID STRIPPED_JUNGLE_WOOD = RegisterBlock("minecraft:stripped_jungle_wood", new MaterialNone(), false, true, false);
    BlockID STRIPPED_MANGROVE_WOOD = RegisterBlock("minecraft:stripped_mangrove_wood", new MaterialNone(), false, true, false);
    BlockID STRIPPED_SPRUCE_WOOD = RegisterBlock("minecraft:stripped_spruce_wood", new MaterialNone(), false, true, false);
    BlockID BRICKS = RegisterBlock("minecraft:bricks", new MaterialNone(), false, true, false);
    BlockID STONE_BRICKS = RegisterBlock("minecraft:stone_bricks", new MaterialNone(), false, true, false);
    BlockID CRACKED_STONE_BRICKS = RegisterBlock("minecraft:cracked_stone_bricks", new MaterialNone(), false, true, false);
    BlockID CHISELED_STONE_BRICKS = RegisterBlock("minecraft:chiseled_stone_bricks", new MaterialNone(), false, true, false);
    BlockID MOSSY_STONE_BRICKS = RegisterBlock("minecraft:mossy_stone_bricks", new MaterialNone(), false, true, false);
    BlockID DEEPSLATE_BRICKS = RegisterBlock("minecraft:deepslate_bricks", new MaterialNone(), false, true, false);
    BlockID CRACKED_DEEPSLATE_BRICKS = RegisterBlock("minecraft:cracked_deepslate_bricks", new MaterialNone(), false, true, false);
    BlockID TUFF_BRICKS = RegisterBlock("minecraft:tuff_bricks", new MaterialNone(), false, true, false);
    BlockID CHISELED_TUFF_BRICKS = RegisterBlock("minecraft:chiseled_tuff_bricks", new MaterialNone(), false, true, false);
    BlockID MUD_BRICKS = RegisterBlock("minecraft:mud_bricks", new MaterialNone(), false, true, false);
    BlockID PRISMARINE_BRICKS = RegisterBlock("minecraft:prismarine_bricks", new MaterialNone(), false, true, false);
    BlockID NETHER_BRICKS = RegisterBlock("minecraft:nether_bricks", new MaterialNone(), false, true, false);
    BlockID CRACKED_NETHER_BRICKS = RegisterBlock("minecraft:cracked_nether_bricks", new MaterialNone(), false, true, false);
    BlockID CHISELED_NETHER_BRICKS = RegisterBlock("minecraft:chiseled_nether_bricks", new MaterialNone(), false, true, false);
    BlockID RED_NETHER_BRICKS = RegisterBlock("minecraft:red_nether_bricks", new MaterialNone(), false, true, false);
    BlockID POLISHED_BLACKSTONE_BRICK = RegisterBlock("minecraft:polished_blackstone_bricks", new MaterialNone(), false, true, false);
    BlockID CRACKED_POLISHED_BLACKSTONE_BRICK = RegisterBlock("minecraft:cracked_polished_blackstone_bricks", new MaterialNone(), false, true, false);
    BlockID END_STONE_BRICKS = RegisterBlock("minecraft:end_stone_bricks", new MaterialNone(), false, true, false);
    BlockID COBBLESTONE = RegisterBlock("minecraft:cobblestone", new MaterialNone(), false, true, false);
    BlockID BLUE_STAINED_GLASS = RegisterBlock("minecraft:blue_stained_glass", new MaterialNone(), true, true, false);
    BlockID GREEN_STAINED_GLASS = RegisterBlock("minecraft:green_stained_glass", new MaterialNone(), true, true, false);
    BlockID BLACK_STAINED_GLASS = RegisterBlock("minecraft:black_stained_glass", new MaterialNone(), true, true, false);
    BlockID BROWN_STAINED_GLASS = RegisterBlock("minecraft:brown_stained_glass", new MaterialNone(), true, true, false);
    BlockID CYAN_STAINED_GLASS = RegisterBlock("minecraft:cyan_stained_glass", new MaterialNone(), true, true, false);
    BlockID GRAY_STAINED_GLASS = RegisterBlock("minecraft:gray_stained_glass", new MaterialNone(), true, true, false);
    BlockID LIGHT_BLUE_STAINED_GLASS = RegisterBlock("minecraft:light_blue_stained_glass", new MaterialNone(), true, true, false);
    BlockID LIGHT_GRAY_STAINED_GLASS = RegisterBlock("minecraft:light_gray_stained_glass", new MaterialNone(), true, true, false);
    BlockID LIME_STAINED_GLASS = RegisterBlock("minecraft:lime_stained_glass", new MaterialNone(), true, true, false);
    BlockID MAGENTA_STAINED_GLASS = RegisterBlock("minecraft:magenta_stained_glass", new MaterialNone(), true, true, false);
    BlockID ORANGE_STAINED_GLASS = RegisterBlock("minecraft:orange_stained_glass", new MaterialNone(), true, true, false);
    BlockID PINK_STAINED_GLASS = RegisterBlock("minecraft:pink_stained_glass", new MaterialNone(), true, true, false);
    BlockID PURPLE_STAINED_GLASS = RegisterBlock("minecraft:purple_stained_glass", new MaterialNone(), true, true, false);
    BlockID RED_STAINED_GLASS = RegisterBlock("minecraft:red_stained_glass", new MaterialNone(), true, true, false);
    BlockID WHITE_STAINED_GLASS = RegisterBlock("minecraft:white_stained_glass", new MaterialNone(), true, true, false);
    BlockID YELLOW_STAINED_GLASS = RegisterBlock("minecraft:yellow_stained_glass", new MaterialNone(), true, true, false);
    BlockID WHITE_WOOL = RegisterBlock("minecraft:white_wool", new MaterialNone(), false, true, false);
    BlockID BLACK_WOOL = RegisterBlock("minecraft:black_wool", new MaterialNone(), false, true, false);
    BlockID BLUE_WOOL = RegisterBlock("minecraft:blue_wool", new MaterialNone(), false, true, false);
    BlockID BROWN_WOOL = RegisterBlock("minecraft:brown_wool", new MaterialNone(), false, true, false);
    BlockID CYAN_WOOL = RegisterBlock("minecraft:cyan_wool", new MaterialNone(), false, true, false);
    BlockID GRAY_WOOL = RegisterBlock("minecraft:gray_wool", new MaterialNone(), false, true, false);
    BlockID GREEN_WOOL = RegisterBlock("minecraft:green_wool", new MaterialNone(), false, true, false);
    BlockID LIGHT_BLUE_WOOL = RegisterBlock("minecraft:light_blue_wool", new MaterialNone(), false, true, false);
    BlockID LIGHT_GRAY_WOOL = RegisterBlock("minecraft:light_gray_wool", new MaterialNone(), false, true, false);
    BlockID LIME_WOOL = RegisterBlock("minecraft:lime_wool", new MaterialNone(), false, true, false);
    BlockID MAGENTA_WOOL = RegisterBlock("minecraft:magenta_wool", new MaterialNone(), false, true, false);
    BlockID ORANGE_WOOL = RegisterBlock("minecraft:orange_wool", new MaterialNone(), false, true, false);
    BlockID PINK_WOOL = RegisterBlock("minecraft:pink_wool", new MaterialNone(), false, true, false);
    BlockID PURPLE_WOOL = RegisterBlock("minecraft:purple_wool", new MaterialNone(), false, true, false);
    BlockID RED_WOOL = RegisterBlock("minecraft:red_wool", new MaterialNone(), false, true, false);
    BlockID YELLOW_WOOL = RegisterBlock("minecraft:yellow_wool", new MaterialNone(), false, true, false);
    BlockID WHITE_TERRACOTTA = RegisterBlock("minecraft:white_terracotta", new MaterialNone(), false, true, false);
    BlockID BLACK_TERRACOTTA = RegisterBlock("minecraft:black_terracotta", new MaterialNone(), false, true, false);
    BlockID BLUE_TERRACOTTA = RegisterBlock("minecraft:blue_terracotta", new MaterialNone(), false, true, false);
    BlockID BROWN_TERRACOTTA = RegisterBlock("minecraft:brown_terracotta", new MaterialNone(), false, true, false);
    BlockID CYAN_TERRACOTTA = RegisterBlock("minecraft:cyan_terracotta", new MaterialNone(), false, true, false);
    BlockID GRAY_TERRACOTTA = RegisterBlock("minecraft:gray_terracotta", new MaterialNone(), false, true, false);
    BlockID GREEN_TERRACOTTA = RegisterBlock("minecraft:green_terracotta", new MaterialNone(), false, true, false);
    BlockID LIGHT_BLUE_TERRACOTTA = RegisterBlock("minecraft:light_blue_terracotta", new MaterialNone(), false, true, false);
    BlockID LIGHT_GRAY_TERRACOTTA = RegisterBlock("minecraft:light_gray_terracotta", new MaterialNone(), false, true, false);
    BlockID LIME_TERRACOTTA = RegisterBlock("minecraft:lime_terracotta", new MaterialNone(), false, true, false);
    BlockID MAGENTA_TERRACOTTA = RegisterBlock("minecraft:magenta_terracotta", new MaterialNone(), false, true, false);
    BlockID ORANGE_TERRACOTTA = RegisterBlock("minecraft:orange_terracotta", new MaterialNone(), false, true, false);
    BlockID PINK_TERRACOTTA = RegisterBlock("minecraft:pink_terracotta", new MaterialNone(), false, true, false);
    BlockID PURPLE_TERRACOTTA = RegisterBlock("minecraft:purple_terracotta", new MaterialNone(), false, true, false);
    BlockID RED_TERRACOTTA = RegisterBlock("minecraft:red_terracotta", new MaterialNone(), false, true, false);
    BlockID YELLOW_TERRACOTTA = RegisterBlock("minecraft:yellow_terracotta", new MaterialNone(), false, true, false);
    BlockID WHITE_GLAZED_TERRACOTTA = RegisterBlock("minecraft:white_glazed_terracotta", new MaterialNone(), false, true, false);
    BlockID BLACK_GLAZED_TERRACOTTA = RegisterBlock("minecraft:black_glazed_terracotta", new MaterialNone(), false, true, false);
    BlockID BLUE_GLAZED_TERRACOTTA = RegisterBlock("minecraft:blue_glazed_terracotta", new MaterialNone(), false, true, false);
    BlockID BROWN_GLAZED_TERRACOTTA = RegisterBlock("minecraft:brown_glazed_terracotta", new MaterialNone(), false, true, false);
    BlockID CYAN_GLAZED_TERRACOTTA = RegisterBlock("minecraft:cyan_glazed_terracotta", new MaterialNone(), false, true, false);
    BlockID GRAY_GLAZED_TERRACOTTA = RegisterBlock("minecraft:gray_glazed_terracotta", new MaterialNone(), false, true, false);
    BlockID GREEN_GLAZED_TERRACOTTA = RegisterBlock("minecraft:green_glazed_terracotta", new MaterialNone(), false, true, false);
    BlockID LIGHT_BLUE_GLAZED_TERRACOTTA = RegisterBlock("minecraft:light_blue_glazed_terracotta", new MaterialNone(), false, true, false);
    BlockID LIGHT_GRAY_GLAZED_TERRACOTTA = RegisterBlock("minecraft:light_gray_glazed_terracotta", new MaterialNone(), false, true, false);
    BlockID LIME_GLAZED_TERRACOTTA = RegisterBlock("minecraft:lime_glazed_terracotta", new MaterialNone(), false, true, false);
    BlockID MAGENTA_GLAZED_TERRACOTTA = RegisterBlock("minecraft:magenta_glazed_terracotta", new MaterialNone(), false, true, false);
    BlockID ORANGE_GLAZED_TERRACOTTA = RegisterBlock("minecraft:orange_glazed_terracotta", new MaterialNone(), false, true, false);
    BlockID PINK_GLAZED_TERRACOTTA = RegisterBlock("minecraft:pink_glazed_terracotta", new MaterialNone(), false, true, false);
    BlockID PURPLE_GLAZED_TERRACOTTA = RegisterBlock("minecraft:purple_glazed_terracotta", new MaterialNone(), false, true, false);
    BlockID RED_GLAZED_TERRACOTTA = RegisterBlock("minecraft:red_glazed_terracotta", new MaterialNone(), false, true, false);
    BlockID YELLOW_GLAZED_TERRACOTTA = RegisterBlock("minecraft:yellow_glazed_terracotta", new MaterialNone(), false, true, false);
    BlockID TERRACOTTA = RegisterBlock("minecraft:terracotta", new MaterialNone(), false, true, false);
    BlockID WHITE_CONCRETE = RegisterBlock("minecraft:white_concrete", new MaterialNone(), false, true, false);
    BlockID BLACK_CONCRETE = RegisterBlock("minecraft:black_concrete", new MaterialNone(), false, true, false);
    BlockID BLUE_CONCRETE = RegisterBlock("minecraft:blue_concrete", new MaterialNone(), false, true, false);
    BlockID BROWN_CONCRETE = RegisterBlock("minecraft:brown_concrete", new MaterialNone(), false, true, false);
    BlockID CYAN_CONCRETE = RegisterBlock("minecraft:cyan_concrete", new MaterialNone(), false, true, false);
    BlockID GRAY_CONCRETE = RegisterBlock("minecraft:gray_concrete", new MaterialNone(), false, true, false);
    BlockID GREEN_CONCRETE = RegisterBlock("minecraft:green_concrete", new MaterialNone(), false, true, false);
    BlockID LIGHT_BLUE_CONCRETE = RegisterBlock("minecraft:light_blue_concrete", new MaterialNone(), false, true, false);
    BlockID LIGHT_GRAY_CONCRETE = RegisterBlock("minecraft:light_gray_concrete", new MaterialNone(), false, true, false);
    BlockID LIME_CONCRETE = RegisterBlock("minecraft:lime_concrete", new MaterialNone(), false, true, false);
    BlockID MAGENTA_CONCRETE = RegisterBlock("minecraft:magenta_concrete", new MaterialNone(), false, true, false);
    BlockID ORANGE_CONCRETE = RegisterBlock("minecraft:orange_concrete", new MaterialNone(), false, true, false);
    BlockID PINK_CONCRETE = RegisterBlock("minecraft:pink_concrete", new MaterialNone(), false, true, false);
    BlockID PURPLE_CONCRETE = RegisterBlock("minecraft:purple_concrete", new MaterialNone(), false, true, false);
    BlockID RED_CONCRETE = RegisterBlock("minecraft:red_concrete", new MaterialNone(), false, true, false);
    BlockID YELLOW_CONCRETE = RegisterBlock("minecraft:yellow_concrete", new MaterialNone(), false, true, false);
    BlockID WHITE_CONCRETE_POWDER = RegisterBlock("minecraft:white_concrete_powder", new MaterialNone(), false, true, false); //FIX POWDERS LATER
    BlockID BLACK_CONCRETE_POWDER = RegisterBlock("minecraft:black_concrete_powder", new MaterialNone(), false, true, false);
    BlockID BLUE_CONCRETE_POWDER = RegisterBlock("minecraft:blue_concrete_powder", new MaterialNone(), false, true, false);
    BlockID BROWN_CONCRETE_POWDER = RegisterBlock("minecraft:brown_concrete_powder", new MaterialNone(), false, true, false);
    BlockID CYAN_CONCRETE_POWDER = RegisterBlock("minecraft:cyan_concrete_powder", new MaterialNone(), false, true, false);
    BlockID GRAY_CONCRETE_POWDER = RegisterBlock("minecraft:gray_concrete_powder", new MaterialNone(), false, true, false);
    BlockID GREEN_CONCRETE_POWDER = RegisterBlock("minecraft:green_concrete_powder", new MaterialNone(), false, true, false);
    BlockID LIGHT_BLUE_CONCRETE_POWDER = RegisterBlock("minecraft:light_blue_concrete_powder", new MaterialNone(), false, true, false);
    BlockID LIGHT_GRAY_CONCRETE_POWDER = RegisterBlock("minecraft:light_gray_concrete_powder", new MaterialNone(), false, true, false);
    BlockID LIME_CONCRETE_POWDER = RegisterBlock("minecraft:lime_concrete_powder", new MaterialNone(), false, true, false);
    BlockID MAGENTA_CONCRETE_POWDER = RegisterBlock("minecraft:magenta_concrete_powder", new MaterialNone(), false, true, false);
    BlockID ORANGE_CONCRETE_POWDER = RegisterBlock("minecraft:orange_concrete_powder", new MaterialNone(), false, true, false);
    BlockID PINK_CONCRETE_POWDER = RegisterBlock("minecraft:pink_concrete_powder", new MaterialNone(), false, true, false);
    BlockID PURPLE_CONCRETE_POWDER = RegisterBlock("minecraft:purple_concrete_powder", new MaterialNone(), false, true, false);
    BlockID RED_CONCRETE_POWDER = RegisterBlock("minecraft:red_concrete_powder", new MaterialNone(), false, true, false);
    BlockID YELLOW_CONCRETE_POWDER = RegisterBlock("minecraft:yellow_concrete_powder", new MaterialNone(), false, true, false);
    BlockID PODZOL = RegisterBlock("minecraft:podzol", new MaterialNone(), false, true, false);
    BlockID MYCELIUM = RegisterBlock("minecraft:mycelium", new MaterialNone(), false, true, false);
    BlockID DIRT_PATH = RegisterBlock("minecraft:dirt_path", new MaterialNone(), false, true, false);
    BlockID COARSE_DIRT = RegisterBlock("minecraft:coarse_dirt", new MaterialNone(), false, true, false);
    BlockID ROOTED_DIRT = RegisterBlock("minecraft:rooted_dirt", new MaterialNone(), false, true, false);
    BlockID FARMLAND = RegisterBlock("minecraft:farmland", new MaterialNone(), false, true, false);
    BlockID FARMLAND_MOIST = RegisterBlock("minecraft:farmland_moist", new MaterialNone(), false, true, false);
    BlockID MUD = RegisterBlock("minecraft:mud", new MaterialNone(), false, true, false);
    BlockID CLAY = RegisterBlock("minecraft:clay", new MaterialNone(), false, true, false);
    BlockID GRAVEL = RegisterBlock("minecraft:gravel", new MaterialNone(), false, true, false); //Change to falling block later
    BlockID RED_SAND = RegisterBlock("minecraft:red_sand", new MaterialNone(), false, true, false); //Change to falling block later
    BlockID ICE = RegisterBlock("minecraft:ice", new MaterialNone(), true, true, false);
    BlockID BLUE_ICE = RegisterBlock("minecraft:blue_ice", new MaterialNone(), false, true, false);
    BlockID SNOW_BLOCK = RegisterBlock("minecraft:snow_block", new MaterialNone(), false, true, false);
    BlockID MOSS_BLOCK = RegisterBlock("minecraft:moss_block", new MaterialNone(), false, true, false);
    BlockID GRANITE = RegisterBlock("minecraft:granite", new MaterialNone(), false, true, false);
    BlockID DIORITE = RegisterBlock("minecraft:diorite", new MaterialNone(), false, true, false);
    BlockID ANDESITE = RegisterBlock("minecraft:andesite", new MaterialNone(), false, true, false);
    BlockID CALCITE = RegisterBlock("minecraft:calcite", new MaterialNone(), false, true, false);
    BlockID DRIPSTONE_BLOCK = RegisterBlock("minecraft:dripstone_block", new MaterialNone(), false, true, false);
    BlockID PRISMARINE = RegisterBlock("minecraft:prismarine", new MaterialNone(), false, true, false);
    BlockID MAGMA = RegisterBlock("minecraft:magma_block", new MaterialNone(), false, true, false); //special properties
    BlockID OBSIDIAN = RegisterBlock("minecraft:obsidian", new MaterialNone(), false, true, false);
    BlockID CRYING_OBSIDIAN = RegisterBlock("minecraft:crying_obsidian", new MaterialNone(), false, true, false);
    BlockID NETHERRACK = RegisterBlock("minecraft:netherrack", new MaterialNone(), false, true, false);
    BlockID CRIMSON_NYLIUM = RegisterBlock("minecraft:crimson_nylium", new MaterialNone(), false, true, false);
    BlockID WARPED_NYLIUM = RegisterBlock("minecraft:warped_nylium", new MaterialNone(), false, true, false);
    BlockID SOUL_SAND = RegisterBlock("minecraft:soul_sand", new MaterialNone(), false, true, false);
    BlockID SOUL_SOIL = RegisterBlock("minecraft:soul_soil", new MaterialNone(), false, true, false);
    BlockID BONE_BLOCK = RegisterBlock("minecraft:bone_block", new MaterialNone(), false, true, false);
    BlockID BLACKSTONE = RegisterBlock("minecraft:blackstone", new MaterialNone(), false, true, false);
    BlockID BASALT = RegisterBlock("minecraft:basalt", new MaterialNone(), false, true, false);
    BlockID SMOOTH_BASALT = RegisterBlock("minecraft:smooth_basalt", new MaterialNone(), false, true, false);
    BlockID END_STONE = RegisterBlock("minecraft:end_stone", new MaterialNone(), false, true, false);
    BlockID COAL_ORE = RegisterBlock("minecraft:coal_ore", new MaterialNone(), false, true, false);
    BlockID DEEPSLATE_COAL_ORE = RegisterBlock("minecraft:deepslate_coal_ore", new MaterialNone(), false, true, false);
    BlockID IRON_ORE = RegisterBlock("minecraft:iron_ore", new MaterialNone(), false, true, false);
    BlockID DEEPSLATE_IRON_ORE = RegisterBlock("minecraft:deepslate_iron_ore", new MaterialNone(), false, true, false);
    BlockID COPPER_ORE = RegisterBlock("minecraft:copper_ore", new MaterialNone(), false, true, false);
    BlockID DEEPSLATE_COPPER_ORE = RegisterBlock("minecraft:deepslate_copper_ore", new MaterialNone(), false, true, false);
    BlockID GOLD_ORE = RegisterBlock("minecraft:gold_ore", new MaterialNone(), false, true, false);
    BlockID DEEPSLATE_GOLD_ORE = RegisterBlock("minecraft:deepslate_gold_ore", new MaterialNone(), false, true, false);
    BlockID REDSTONE_ORE = RegisterBlock("minecraft:redstone_ore", new MaterialNone(), false, true, false);
    BlockID DEEPSLATE_REDSTONE_ORE = RegisterBlock("minecraft:deepslate_redstone_ore", new MaterialNone(), false, true, false);
    BlockID EMERALD_ORE = RegisterBlock("minecraft:emerald_ore", new MaterialNone(), false, true, false);
    BlockID DEEPSLATE_EMERALD_ORE = RegisterBlock("minecraft:deepslate_emerald_ore", new MaterialNone(), false, true, false);
    BlockID LAPIS_ORE = RegisterBlock("minecraft:lapis_ore", new MaterialNone(), false, true, false);
    BlockID DEEPSLATE_LAPIS_ORE = RegisterBlock("minecraft:deepslate_lapis_ore", new MaterialNone(), false, true, false);
    BlockID DIAMOND_ORE = RegisterBlock("minecraft:diamond_ore", new MaterialNone(), false, true, false);
    BlockID DEEPSLATE_DIAMOND_ORE = RegisterBlock("minecraft:deepslate_diamond_ore", new MaterialNone(), false, true, false);
    BlockID NETHER_GOLD_ORE = RegisterBlock("minecraft:nether_gold_ore", new MaterialNone(), false, true, false);
    BlockID NETHER_QUARTZ_ORE = RegisterBlock("minecraft:nether_quartz_ore", new MaterialNone(), false, true, false);
    BlockID ANCIENT_DEBRIS = RegisterBlock("minecraft:ancient_debris", new MaterialNone(), false, true, false);
    BlockID RAW_IRON_BLOCK = RegisterBlock("minecraft:raw_iron_block", new MaterialNone(), false, true, false);
    BlockID RAW_COPPER_BLOCK = RegisterBlock("minecraft:raw_copper_block", new MaterialNone(), false, true, false);
    BlockID RAW_GOLD_BLOCK = RegisterBlock("minecraft:raw_gold_block", new MaterialNone(), false, true, false);
    BlockID GLOWSTONE = RegisterBlock("minecraft:glowstone", new MaterialNone(), false, true, false);
    BlockID AMETHYST_BLOCK = RegisterBlock("minecraft:amethyst_block", new MaterialNone(), false, true, false);
    BlockID BUDDING_AMETHYST = RegisterBlock("minecraft:budding_amethyst", new MaterialNone(), false, true, false);
    BlockID SPRUCE_LOG = RegisterBlock("minecraft:spruce_log", new MaterialNone(), false, true, false);
    BlockID STRIPPED_SPRUCE_LOG = RegisterBlock("minecraft:stripped_spruce_log", new MaterialNone(), false, true, false);
    BlockID BIRCH_LOG = RegisterBlock("minecraft:birch_log", new MaterialNone(), false, true, false);
    BlockID STRIPPED_BIRCH_LOG = RegisterBlock("minecraft:stripped_birch_log", new MaterialNone(), false, true, false);
    BlockID JUNGLE_LOG = RegisterBlock("minecraft:jungle_log", new MaterialNone(), false, true, false);
    BlockID STRIPPED_JUNGLE_LOG = RegisterBlock("minecraft:stripped_jungle_log", new MaterialNone(), false, true, false);
    BlockID ACACIA_LOG = RegisterBlock("minecraft:acacia_log", new MaterialNone(), false, true, false);
    BlockID STRIPPED_ACACIA_LOG = RegisterBlock("minecraft:stripped_acacia_log", new MaterialNone(), false, true, false);
    BlockID DARK_OAK_LOG = RegisterBlock("minecraft:dark_oak_log", new MaterialNone(), false, true, false);
    BlockID STRIPPED_DARK_OAK_LOG = RegisterBlock("minecraft:stripped_dark_oak_log", new MaterialNone(), false, true, false);
    BlockID CHERRY_LOG = RegisterBlock("minecraft:cherry_log", new MaterialNone(), false, true, false);
    BlockID STRIPPED_CHERRY_LOG = RegisterBlock("minecraft:stripped_cherry_log", new MaterialNone(), false, true, false);
    BlockID MANGROVE_LOG = RegisterBlock("minecraft:mangrove_log", new MaterialNone(), false, true, false);
    BlockID STRIPPED_MANGROVE_LOG = RegisterBlock("minecraft:stripped_mangrove_log", new MaterialNone(), false, true, false);
    BlockID CRIMSON_STEM = RegisterBlock("minecraft:crimson_stem", new MaterialNone(), false, true, false);
    BlockID STRIPPED_CRIMSON_STEM = RegisterBlock("minecraft:stripped_crimson_stem", new MaterialNone(), false, true, false);
    BlockID WARPED_STEM = RegisterBlock("minecraft:warped_stem", new MaterialNone(), false, true, false);
    BlockID STRIPPED_WARPED_STEM = RegisterBlock("minecraft:stripped_warped_stem", new MaterialNone(), false, true, false);
    BlockID MANGROVE_ROOTS = RegisterBlock("minecraft:mangrove_roots", new MaterialNone(), true, true, false);
    BlockID MUDDY_MANGROVE_ROOTS = RegisterBlock("minecraft:muddy_mangrove_roots", new MaterialNone(), false, true, false);
    BlockID MUSHROOM_STEM = RegisterBlock("minecraft:mushroom_stem", new MaterialNone(), false, true, false);
    BlockID BROWN_MUSHROOM_BLOCK = RegisterBlock("minecraft:brown_mushroom_block", new MaterialNone(), false, true, false);
    BlockID RED_MUSHROOM_BLOCK = RegisterBlock("minecraft:red_mushroom_block", new MaterialNone(), false, true, false);
    BlockID NETHER_WART_BLOCK = RegisterBlock("minecraft:nether_wart_block", new MaterialNone(), false, true, false);
    BlockID WARPED_WART_BLOCK = RegisterBlock("minecraft:warped_wart_block", new MaterialNone(), false, true, false);
    BlockID SHROOMLIGHT = RegisterBlock("minecraft:shroomlight", new MaterialNone(), false, true, false);
    BlockID DRIED_KELP_BLOCK = RegisterBlock("minecraft:dried_kelp_block", new MaterialNone(), false, true, false);
    BlockID TUBE_CORAL_BLOCK = RegisterBlock("minecraft:tube_coral_block", new MaterialNone(), false, true, false);
    BlockID BRAIN_CORAL_BLOCK = RegisterBlock("minecraft:brain_coral_block", new MaterialNone(), false, true, false);
    BlockID BUBBLE_CORAL_BLOCK = RegisterBlock("minecraft:bubble_coral_block", new MaterialNone(), false, true, false);
    BlockID FIRE_CORAL_BLOCK = RegisterBlock("minecraft:fire_coral_block", new MaterialNone(), false, true, false);
    BlockID HORN_CORAL_BLOCK = RegisterBlock("minecraft:horn_coral_block", new MaterialNone(), false, true, false);
    BlockID DEAD_TUBE_CORAL_BLOCK = RegisterBlock("minecraft:dead_tube_coral_block", new MaterialNone(), false, true, false);
    BlockID DEAD_BRAIN_CORAL_BLOCK = RegisterBlock("minecraft:dead_brain_coral_block", new MaterialNone(), false, true, false);
    BlockID DEAD_BUBBLE_CORAL_BLOCK = RegisterBlock("minecraft:dead_bubble_coral_block", new MaterialNone(), false, true, false);
    BlockID DEAD_FIRE_CORAL_BLOCK = RegisterBlock("minecraft:dead_fire_coral_block", new MaterialNone(), false, true, false);
    BlockID DEAD_HORN_CORAL_BLOCK = RegisterBlock("minecraft:dead_horn_coral_block", new MaterialNone(), false, true, false);
    BlockID SPONGE = RegisterBlock("minecraft:sponge", new MaterialNone(), false, true, false);
    BlockID WET_SPONGE = RegisterBlock("minecraft:wet_sponge", new MaterialNone(), false, true, false);
    BlockID MELON = RegisterBlock("minecraft:melon", new MaterialNone(), false, true, false);
    BlockID PUMPKIN = RegisterBlock("minecraft:pumpkin", new MaterialNone(), false, true, false);
    BlockID CARVED_PUMPKIN = RegisterBlock("minecraft:carved_pumpkin", new MaterialNone(), false, true, false);
    BlockID JACK_O_LANTERN = RegisterBlock("minecraft:jack_o_lantern", new MaterialNone(), false, true, false);
    BlockID HAY_BALE = RegisterBlock("minecraft:hay_block", new MaterialNone(), false, true, false);
    BlockID BEE_NEST = RegisterBlock("minecraft:bee_nest", new MaterialNone(), false, true, false);
    BlockID HONEYCOMB_BLOCK = RegisterBlock("minecraft:honeycomb_block", new MaterialNone(), false, true, false);
    BlockID OCHRE_FROGLIGHT = RegisterBlock("minecraft:ochre_froglight", new MaterialNone(), false, true, false);
    BlockID VERDANT_FROGLIGHT = RegisterBlock("minecraft:verdant_froglight", new MaterialNone(), false, true, false);
    BlockID PEARLESCENT_FROGLIGHT = RegisterBlock("minecraft:pearlescent_froglight", new MaterialNone(), false, true, false);
    BlockID SCULK = RegisterBlock("minecraft:sculk", new MaterialNone(), false, true, false);
    BlockID SCULK_CATALYST = RegisterBlock("minecraft:sculk_catalyst", new MaterialNone(), false, true, false);
    BlockID BEDROCK = RegisterBlock("minecraft:bedrock", new MaterialNone(), false, true, false);
    BlockID SPRUCE_LEAVES = RegisterBlock("minecraft:spruce_leaves", new MaterialNone(), true, true, false);
    BlockID BIRCH_LEAVES = RegisterBlock("minecraft:birch_leaves", new MaterialNone(), true, true, false);
    BlockID JUNGLE_LEAVES = RegisterBlock("minecraft:jungle_leaves", new MaterialNone(), true, true, false);
    BlockID ACACIA_LEAVES = RegisterBlock("minecraft:acacia_leaves", new MaterialNone(), true, true, false);
    BlockID DARK_OAK_LEAVES = RegisterBlock("minecraft:dark_oak_leaves", new MaterialNone(), true, true, false);
    BlockID MANGROVE_LEAVES = RegisterBlock("minecraft:mangrove_leaves", new MaterialNone(), true, true, false);
    BlockID CHERRY_LEAVES = RegisterBlock("minecraft:cherry_leaves", new MaterialNone(), true, true, false);
    BlockID AZALEA_LEAVES = RegisterBlock("minecraft:azalea_leaves", new MaterialNone(), true, true, false);
    BlockID FLOWERING_AZALEA_LEAVES = RegisterBlock("minecraft:flowering_azalea_leaves", new MaterialNone(), true, true, false);
    BlockID OAK_LEAF = RegisterBlock("minecraft:oak_leaves", new MaterialNone(), true, true, false);
    BlockID SEA_LANTERN = RegisterBlock("minecraft:sea_lantern", new MaterialNone(), false, true, false);
    BlockID REDSTONE_LAMP = RegisterBlock("minecraft:redstone_lamp", new MaterialNone(), false, true, false);
    BlockID CRAFTING_TABLE = RegisterBlock("minecraft:crafting_table", new MaterialNone(), false, true, false);
    BlockID COPPER_BULB = RegisterBlock("minecraft:copper_bulb", new MaterialNone(), false, true, false);
    BlockID EXPOSED_COPPER_BULB = RegisterBlock("minecraft:exposed_copper_bulb", new MaterialNone(), false, true, false);
    BlockID OXIDIZED_COPPER_BULB = RegisterBlock("minecraft:oxidized_copper_bulb", new MaterialNone(), false, true, false);
    BlockID WEATHERED_COPPER_BULB = RegisterBlock("minecraft:weathered_copper_bulb", new MaterialNone(), false, true, false);
    BlockID COPPER_GRATE = RegisterBlock("minecraft:copper_grate", new MaterialNone(), true, true, false);
    BlockID EXPOSED_COPPER_GRATE = RegisterBlock("minecraft:exposed_copper_grate", new MaterialNone(), true, true, false);
    BlockID OXIDIZED_COPPER_GRATE = RegisterBlock("minecraft:oxidized_copper_grate", new MaterialNone(), true, true, false);
    BlockID WEATHERED_COPPER_GRATE = RegisterBlock("minecraft:weathered_copper_grate", new MaterialNone(), true, true, false);
    BlockID CUT_COPPER = RegisterBlock("minecraft:cut_copper", new MaterialNone(), false, true, false);
    BlockID EXPOSED_CUT_COPPER = RegisterBlock("minecraft:exposed_cut_copper", new MaterialNone(), false, true, false);
    BlockID OXIDIZED_CUT_COPPER = RegisterBlock("minecraft:oxidized_cut_copper", new MaterialNone(), false, true, false);
    BlockID WEATHERED_CUT_COPPER = RegisterBlock("minecraft:weathered_cut_copper", new MaterialNone(), false, true, false);
    BlockID CHISELED_COPPER = RegisterBlock("minecraft:chiseled_copper", new MaterialNone(), false, true, false);
    BlockID EXPOSED_CHISELED_COPPER = RegisterBlock("minecraft:exposed_chiseled_copper", new MaterialNone(), false, true, false);
    BlockID OXIDIZED_CHISELED_COPPER = RegisterBlock("minecraft:oxidized_chiseled_copper", new MaterialNone(), false, true, false);
    BlockID WEATHERED_CHISELED_COPPER = RegisterBlock("minecraft:weathered_chiseled_copper", new MaterialNone(), false, true, false);
    BlockID WARPED_HYPHAE = RegisterBlock("minecraft:warped_hyphae", new MaterialNone(), false, true, false);
    BlockID STRIPPED_WARPED_HYPHAE = RegisterBlock("minecraft:stripped_warped_hyphae", new MaterialNone(), false, true, false);
    BlockID CRIMSON_HYPHAE = RegisterBlock("minecraft:crimson_hyphae", new MaterialNone(), false, true, false);
    BlockID STRIPPED_CRIMSON_HYPHAE = RegisterBlock("minecraft:stripped_crimson_hyphae", new MaterialNone(), false, true, false);
    BlockID MOSSY_COBBLESTONE = RegisterBlock("minecraft:mossy_cobblestone", new MaterialNone(), false, true, false);
    BlockID DEEPSLATE = RegisterBlock("minecraft:deepslate", new MaterialNone(), false, true, false);
    BlockID COBBLED_DEEPSLATE = RegisterBlock("minecraft:cobbled_deepslate", new MaterialNone(), false, true, false);
    BlockID CHISELED_DEEPSLATE = RegisterBlock("minecraft:chiseled_deepslate", new MaterialNone(), false, true, false);
    BlockID POLISHED_DEEPSLATE = RegisterBlock("minecraft:polished_deepslate", new MaterialNone(), false, true, false);
    BlockID DEEPSLATE_TILES = RegisterBlock("minecraft:deepslate_tiles", new MaterialNone(), false, true, false);
    BlockID CRACKED_DEEPSLATE_TILES = RegisterBlock("minecraft:deepslate_tiles", new MaterialNone(), false, true, false);
    BlockID REINFORCED_DEEPSLATE = RegisterBlock("minecraft:reinforced_deepslate", new MaterialNone(), false, true, false);
    BlockID TUFF = RegisterBlock("minecraft:tuff", new MaterialNone(), false, true, false);
    BlockID CHISELED_TUFF = RegisterBlock("minecraft:chiseled_tuff", new MaterialNone(), false, true, false);
    BlockID POLISHED_TUFF = RegisterBlock("minecraft:polished_tuff", new MaterialNone(), false, true, false);
    BlockID PACKED_MUD = RegisterBlock("minecraft:packed_mud", new MaterialNone(), false, true, false);
    BlockID SANDSTONE = RegisterBlock("minecraft:sandstone", new MaterialNone(), false, true, false);
    BlockID CHISELED_SANDSTONE = RegisterBlock("minecraft:chiseled_sandstone", new MaterialNone(), false, true, false);
    BlockID SMOOTH_SANDSTONE = RegisterBlock("minecraft:smooth_sandstone", new MaterialNone(), false, true, false);
    BlockID CUT_SANDSTONE = RegisterBlock("minecraft:cut_sandstone", new MaterialNone(), false, true, false);
    BlockID RED_SANDSTONE = RegisterBlock("minecraft:red_sandstone", new MaterialNone(), false, true, false);
    BlockID CHISELED_RED_SANDSTONE = RegisterBlock("minecraft:chiseled_red_sandstone", new MaterialNone(), false, true, false);
    BlockID SMOOTH_RED_SANDSTONE = RegisterBlock("minecraft:smooth_red_sandstone", new MaterialNone(), false, true, false);
    BlockID CUT_RED_SANDSTONE = RegisterBlock("minecraft:cut_red_sandstone", new MaterialNone(), false, true, false);
    BlockID DARK_PRISMARINE = RegisterBlock("minecraft:dark_prismarine", new MaterialNone(), false, true, false);
    BlockID PURPUR_BLOCK = RegisterBlock("minecraft:purpur_block", new MaterialNone(), false, true, false);
    BlockID PURPUR_PILLAR = RegisterBlock("minecraft:purpur_pillar", new MaterialNone(), false, true, false);
    BlockID COAL_BLOCK = RegisterBlock("minecraft:coal_block", new MaterialNone(), false, true, false);
    BlockID IRON_BLOCK = RegisterBlock("minecraft:iron_block", new MaterialNone(), false, true, false);
    BlockID GOLD_BLOCK = RegisterBlock("minecraft:gold_block", new MaterialNone(), false, true, false);
    BlockID REDSTONE_BLOCK = RegisterBlock("minecraft:redstone_block", new MaterialNone(), false, true, false);
    BlockID EMERALD_BLOCK = RegisterBlock("minecraft:emerald_block", new MaterialNone(), false, true, false);
    BlockID LAPIS_BLOCK = RegisterBlock("minecraft:lapis_block", new MaterialNone(), false, true, false);
    BlockID DIAMOND_BLOCK = RegisterBlock("minecraft:diamond_block", new MaterialNone(), false, true, false);
    BlockID NETHERITE_BLOCK = RegisterBlock("minecraft:netherite_block", new MaterialNone(), false, true, false);
    BlockID QUARTZ_BLOCK = RegisterBlock("minecraft:quartz_block", new MaterialNone(), false, true, false);
    BlockID CHISELED_QUARTZ_BLOCK = RegisterBlock("minecraft:chiseled_quartz_block", new MaterialNone(), false, true, false);
    BlockID QUARTZ_PILLAR = RegisterBlock("minecraft:quartz_pillar", new MaterialNone(), false, true, false);
    BlockID SMOOTH_QUARTZ = RegisterBlock("minecraft:smooth_quartz", new MaterialNone(), false, true, false);

    BlockID ANVIL = RegisterBlock("minecraft:anvil", new MaterialNone(), false, true, false);

    void Initialize();

    BlockList();
    ~BlockList();

    void CleanUp();

    Block* GetBlockType(BlockID id);

    const Model::BlockModel& GetBlockModelDereferenced(BlockID id);

    BlockID RegisterBlock(std::string blockName, Material* material, bool transparency, bool solid, bool isFluid);
private:
    int block_type_count_ = 0;

    void InitializeBlockModels();
    void AddAssets(std::string namespaceIn);
} ;

extern BlockList g_blocks;